name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  dart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter pub get
        working-directory: example
      - run: dart format --set-exit-if-changed lib test example/lib example/test example/integration_test
      - run: dart analyze
      - run: flutter test
      - run: flutter test
        working-directory: example

  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter build apk --debug
        working-directory: example

  ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter build ios --debug --no-codesign
        working-directory: example
